# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-11 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170611_1125'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='commentaire',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Titre du commentaire'),
        ),
        migrations.AlterField(
            model_name='jeux',
            name='types',
            field=models.ManyToManyField(to='blog.Type', verbose_name='Type de jeu'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Type de jeu'),
        ),
    ]
